const assert = require('assert')
const fs = require('fs')
const { resolveWorkbenchRole, getWorkbenchConfig } = require('./roleConfig.cjs')

const adminTabs = getWorkbenchConfig('admin').tabs

assert.strictEqual(resolveWorkbenchRole(['client', 'admin']), 'admin')
assert.deepStrictEqual(getWorkbenchConfig('admin').toolbar, ['refresh'])
assert.ok(adminTabs.includes('dashboard'))
assert.ok(adminTabs.includes('businessClients'))
assert.ok(adminTabs.includes('businessTutors'))
assert.ok(adminTabs.includes('businessInvitations'))
assert.ok(adminTabs.includes('businessLessons'))
assert.ok(adminTabs.includes('businessSettlements'))
assert.ok(adminTabs.includes('businessTickets'))
assert.ok(adminTabs.includes('businessAnnouncements'))
assert.ok(adminTabs.includes('businessFollowups'))
assert.ok(adminTabs.includes('businessPayments'))
assert.ok(adminTabs.includes('businessCrm'))
assert.ok(adminTabs.includes('businessRisk'))
assert.ok(adminTabs.includes('businessReports'))
assert.ok(adminTabs.includes('businessReminders'))
assert.ok(adminTabs.includes('businessBlacklists'))
assert.ok(adminTabs.includes('businessLedgers'))
assert.ok(!adminTabs.includes('open'))
assert.ok(getWorkbenchConfig('client').tabs.includes('learners'))
assert.ok(getWorkbenchConfig('client').tabs.includes('tutors'))
assert.ok(getWorkbenchConfig('client').tabs.includes('tickets'))
assert.ok(getWorkbenchConfig('client').tabs.includes('announcements'))
assert.ok(getWorkbenchConfig('client').tabs.includes('calendar'))
assert.ok(getWorkbenchConfig('client').tabs.includes('learning'))
assert.ok(!getWorkbenchConfig('client').tabs.includes('open'))
assert.ok(getWorkbenchConfig('client').actions.learners.includes('edit'))
assert.ok(getWorkbenchConfig('client').actions.requests.includes('copy'))
assert.ok(getWorkbenchConfig('client').actions.matches.includes('confirmLesson'))
assert.ok(getWorkbenchConfig('client').actions.matches.includes('materials'))
assert.ok(getWorkbenchConfig('client').actions.matches.includes('messages'))
assert.ok(getWorkbenchConfig('client').actions.matches.includes('payments'))
assert.ok(getWorkbenchConfig('client').actions.matches.includes('homeworks'))
assert.ok(getWorkbenchConfig('tutor', { tutorVerified: true }).tabs.includes('availability'))
assert.ok(getWorkbenchConfig('tutor', { tutorVerified: true }).tabs.includes('open'))
assert.ok(getWorkbenchConfig('tutor', { tutorVerified: true }).tabs.includes('settlements'))
assert.ok(getWorkbenchConfig('tutor', { tutorVerified: true }).tabs.includes('calendar'))
assert.ok(getWorkbenchConfig('tutor', { tutorVerified: true }).tabs.includes('learning'))
assert.ok(getWorkbenchConfig('tutor', { tutorVerified: true }).tabs.includes('tickets'))
assert.ok(getWorkbenchConfig('tutor', { tutorVerified: true }).tabs.includes('announcements'))
assert.ok(getWorkbenchConfig('tutor', { tutorVerified: true }).actions.matches.includes('materials'))
assert.ok(getWorkbenchConfig('tutor', { tutorVerified: true }).actions.matches.includes('messages'))
assert.ok(getWorkbenchConfig('tutor', { tutorVerified: true }).actions.matches.includes('homeworks'))
assert.ok(getWorkbenchConfig('tutor', { tutorVerified: true }).actions.matches.includes('reschedule'))
assert.deepStrictEqual(getWorkbenchConfig('tutor', { tutorVerified: true }).toolbar, ['refresh'])
assert.deepStrictEqual(getWorkbenchConfig('tutor', { tutorVerified: false }).tabs, ['profile'])
assert.deepStrictEqual(getWorkbenchConfig('tutor', { tutorVerified: false }).toolbar, ['refresh'])

const api = fs.readFileSync('ruoyi-ui/src/api/tutoring.js', 'utf8')
const view = fs.readFileSync('ruoyi-ui/src/views/tutoring/index.vue', 'utf8')
const layout = fs.readFileSync('ruoyi-ui/src/layout/index.vue', 'utf8')

assert.match(api, /listAdminClients/)
assert.match(api, /listAdminTutors/)
assert.match(api, /listAdminInvitations/)
assert.match(api, /listAdminLessons/)
assert.match(api, /changeAdminUserStatus/)
assert.match(api, /closeAdminMatch/)
assert.match(api, /copyRequest/)
assert.match(api, /cancelMatch/)
assert.match(api, /rescheduleMatch/)
assert.match(api, /confirmLesson/)
assert.match(api, /readAllNotifications/)
assert.match(api, /getUnreadNotificationCount/)
assert.match(api, /listLearners/)
assert.match(api, /listAvailability/)
assert.match(api, /scheduleTrial/)
assert.match(api, /listMySettlements/)
assert.match(api, /listTickets/)
assert.match(api, /listAnnouncements/)
assert.match(api, /saveAnnouncement/)
assert.match(api, /listMaterials/)
assert.match(api, /addMaterial/)
assert.match(api, /listAdminFollowups/)
assert.match(api, /listMessages/)
assert.match(api, /addMessage/)
assert.match(api, /listPayments/)
assert.match(api, /addPayment/)
assert.match(api, /mockPayment/)
assert.match(api, /handlePayment/)
assert.match(api, /listCalendarLessons/)
assert.match(api, /listLearningRecords/)
assert.match(api, /getCrmDashboard/)
assert.match(api, /listRiskAlerts/)
assert.match(api, /getOperationsReport/)
assert.match(api, /generateReminders/)
assert.match(api, /completeFollowup/)
assert.match(api, /refundPayment/)
assert.match(api, /reconcilePayment/)
assert.match(api, /batchSettleSettlements/)
assert.match(api, /listHomeworks/)
assert.match(api, /addHomework/)
assert.match(api, /submitHomework/)
assert.match(api, /feedbackHomework/)
assert.match(api, /listAdminBlacklists/)
assert.match(api, /saveBlacklist/)
assert.match(api, /disableBlacklist/)
assert.match(api, /listFinanceLedgers/)
assert.match(api, /issueInvoice/)
assert.match(view, /businessClients/)
assert.match(view, /businessTutors/)
assert.match(view, /businessInvitations/)
assert.match(view, /businessLessons/)
assert.match(view, /learnerRows/)
assert.match(view, /availabilityRows/)
assert.match(view, /settlementRows/)
assert.match(view, /ticketRows/)
assert.match(view, /trialDialog/)
assert.match(view, /studentPerformance/)
assert.match(view, /announcementRows/)
assert.match(view, /materialRows/)
assert.match(view, /followupRows/)
assert.match(view, /messageRows/)
assert.match(view, /paymentRows/)
assert.match(view, /calendarRows/)
assert.match(view, /learningRows/)
assert.match(view, /businessCrm/)
assert.match(view, /businessRisk/)
assert.match(view, /businessReports/)
assert.match(view, /businessReminders/)
assert.match(view, /businessBlacklists/)
assert.match(view, /businessLedgers/)
assert.match(view, /crmCards/)
assert.match(view, /reportCards/)
assert.match(view, /riskAlerts/)
assert.match(view, /reminderCards/)
assert.match(view, /startTime/)
assert.match(view, /endTime/)
assert.match(view, /attendanceStatus/)
assert.match(view, /phaseFeedback/)
assert.match(view, /sourceChannel/)
assert.match(view, /nextTime/)
assert.match(view, /templateCode/)
assert.match(view, /generateReminderRows/)
assert.match(view, /completeFollowupRow/)
assert.match(view, /refundPaymentRow/)
assert.match(view, /reconcilePaymentRow/)
assert.match(view, /batchSettleSelected/)
assert.match(view, /materialDialog/)
assert.match(view, /messageDialog/)
assert.match(view, /paymentDialog/)
assert.match(view, /homeworkDialog/)
assert.match(view, /homeworkRows/)
assert.match(view, /connectChatSocket/)
assert.match(view, /new WebSocket/)
assert.match(view, /submitMockPayment/)
assert.match(view, /openHomeworks/)
assert.match(view, /submitHomeworkForm/)
assert.match(view, /feedbackHomeworkRow/)
assert.match(view, /submitBlacklist/)
assert.match(view, /disableBlacklistRow/)
assert.match(view, /issueInvoiceRow/)
assert.match(view, /file-upload/)
assert.match(view, /workbench-shell/)
assert.match(view, /module-switcher/)
assert.match(view, /workbenchNavItems/)
assert.match(view, /roleMetricCards/)
assert.match(view, /switchTab/)
assert.doesNotMatch(view, /workbench-sidebar/)
assert.match(view, /个人中心/)
assert.match(view, /退出登录/)
assert.match(view, /goProfile/)
assert.match(view, /logout/)
assert.match(layout, /borderlessWorkbench/)
assert.match(layout, /workbench-borderless/)
assert.match(layout, /\/tutoring\/workbench/)
assert.match(view, /changeBusinessUserStatus/)
assert.match(view, /closeBusinessMatch/)
assert.match(view, /copyOwnRequest/)
assert.match(view, /cancelAcceptedMatch/)
assert.match(view, /rescheduleAcceptedMatch/)
assert.match(view, /confirmLessonRow/)
assert.match(view, /markAllRead/)
