const assert = require('assert')
const fs = require('fs')

const repairSql = fs.readFileSync('sql/repair_tutoring_encoding.sql', 'utf8')
const configSql = fs.readFileSync('sql/ry_config_20260611.sql', 'utf8')
const featuresSql = fs.readFileSync('sql/tutoring_features.sql', 'utf8')
const batchSql = fs.readFileSync('sql/tutoring_batch1_batch2_features.sql', 'utf8')
const controller = fs.readFileSync('ruoyi-modules/ruoyi-system/src/main/java/com/ruoyi/system/controller/TutoringController.java', 'utf8')
const webSocket = fs.readFileSync('ruoyi-modules/ruoyi-system/src/main/java/com/ruoyi/system/websocket/TutoringMessageEndpoint.java', 'utf8')

assert.match(repairSql, /tutoring:tutor:list/)
assert.match(repairSql, /tutoring:business:monitor/)
assert.match(repairSql, /2012/)
assert.match(featuresSql, /tutoring:tutor:list/)
assert.match(featuresSql, /tutoring:business:monitor/)
assert.match(featuresSql, /ON DUPLICATE KEY UPDATE/)
assert.match(repairSql, /role_id\s*=\s*101[\s\S]*menu_id\s*=\s*2011|101\s*,\s*2011/)
assert.match(repairSql, /status\s*=\s*VALUES\(status\)/)
assert.match(controller, /@RequiresPermissions\("tutoring:workbench:view"\)\s+@GetMapping\("\/tutors"\)/)
assert.match(controller, /@RequiresPermissions\("tutoring:business:monitor"\)\s+@PutMapping\("\/admin\/users\/\{userId\}\/status"\)/)
assert.match(controller, /@RequiresPermissions\("tutoring:business:monitor"\)\s+@PutMapping\("\/admin\/matches\/\{matchId\}\/close"\)/)
assert.match(controller, /\/admin\/clients/)
assert.match(controller, /\/admin\/tutors/)
assert.match(controller, /\/admin\/invitations/)
assert.match(controller, /\/admin\/lessons/)
assert.match(featuresSql, /availability_text/)
assert.match(featuresSql, /confirm_status/)
assert.match(featuresSql, /cancel_reason/)
assert.match(featuresSql, /reschedule_text/)
assert.match(featuresSql, /tutoring_complaint_log/)
assert.match(featuresSql, /tutoring_learner/)
assert.match(featuresSql, /tutor_availability/)
assert.match(featuresSql, /trial_status/)
assert.match(featuresSql, /student_performance/)
assert.match(featuresSql, /tutoring_settlement/)
assert.match(featuresSql, /tutoring_ticket/)
assert.match(featuresSql, /tutoring_announcement/)
assert.match(featuresSql, /tutoring_material/)
assert.match(featuresSql, /tutoring_followup/)
assert.match(featuresSql, /tutoring_message/)
assert.match(featuresSql, /tutoring_payment/)
assert.match(featuresSql, /start_time/)
assert.match(featuresSql, /platform_fee/)
assert.match(featuresSql, /refund_amount/)
assert.match(featuresSql, /reconciled_status/)
assert.match(featuresSql, /source_channel/)
assert.match(featuresSql, /attendance_status/)
assert.match(featuresSql, /phase_feedback/)
assert.match(featuresSql, /template_code/)
assert.match(featuresSql, /send_status/)
assert.match(featuresSql, /next_time/)
assert.match(featuresSql, /tutoring_blacklist/)
assert.match(featuresSql, /tutoring_homework/)
assert.match(featuresSql, /tutoring_finance_ledger/)
assert.match(batchSql, /availability_text/)
assert.match(batchSql, /confirm_status/)
assert.match(batchSql, /cancel_reason/)
assert.match(batchSql, /reschedule_text/)
assert.match(batchSql, /tutoring_complaint_log/)
assert.match(batchSql, /tutoring_learner/)
assert.match(batchSql, /tutor_availability/)
assert.match(batchSql, /trial_status/)
assert.match(batchSql, /student_performance/)
assert.match(batchSql, /tutoring_settlement/)
assert.match(batchSql, /tutoring_ticket/)
assert.match(batchSql, /tutoring_announcement/)
assert.match(batchSql, /tutoring_material/)
assert.match(batchSql, /tutoring_followup/)
assert.match(batchSql, /tutoring_message/)
assert.match(batchSql, /tutoring_payment/)
assert.match(batchSql, /start_time/)
assert.match(batchSql, /platform_fee/)
assert.match(batchSql, /refund_amount/)
assert.match(batchSql, /reconciled_status/)
assert.match(batchSql, /source_channel/)
assert.match(batchSql, /attendance_status/)
assert.match(batchSql, /phase_feedback/)
assert.match(batchSql, /template_code/)
assert.match(batchSql, /send_status/)
assert.match(batchSql, /next_time/)
assert.match(batchSql, /tutoring_blacklist/)
assert.match(batchSql, /tutoring_homework/)
assert.match(batchSql, /tutoring_finance_ledger/)
assert.match(controller, /\/admin\/export\/\{type\}/)
assert.match(controller, /\/dashboard\/todos/)
assert.match(controller, /\/notifications\/unread-count/)
assert.match(controller, /\/learners\/mine/)
assert.match(controller, /\/availability/)
assert.match(controller, /\/matches\/\{matchId\}\/trial/)
assert.match(controller, /\/settlements\/mine/)
assert.match(controller, /\/tickets\/mine/)
assert.match(controller, /\/announcements/)
assert.match(controller, /\/matches\/\{matchId\}\/materials/)
assert.match(controller, /\/admin\/followups/)
assert.match(controller, /\/matches\/\{matchId\}\/messages/)
assert.match(controller, /\/matches\/\{matchId\}\/payments/)
assert.match(controller, /\/matches\/\{matchId\}\/payments\/mock/)
assert.match(controller, /\/admin\/payments/)
assert.match(controller, /\/calendar\/mine/)
assert.match(controller, /\/learning\/mine/)
assert.match(controller, /\/admin\/crm/)
assert.match(controller, /\/admin\/risk-alerts/)
assert.match(controller, /\/admin\/reports/)
assert.match(controller, /\/admin\/reminders\/generate/)
assert.match(controller, /\/admin\/followups\/\{followupId\}\/done/)
assert.match(controller, /\/admin\/payments\/\{paymentId\}\/refund/)
assert.match(controller, /\/admin\/payments\/\{paymentId\}\/reconcile/)
assert.match(controller, /\/admin\/settlements\/batch\/settle/)
assert.match(controller, /\/matches\/\{matchId\}\/homeworks/)
assert.match(controller, /\/homeworks\/\{homeworkId\}\/submit/)
assert.match(controller, /\/homeworks\/\{homeworkId\}\/feedback/)
assert.match(controller, /\/admin\/blacklists/)
assert.match(controller, /\/admin\/finance-ledgers/)
assert.match(controller, /\/admin\/payments\/\{paymentId\}\/invoice/)
assert.match(webSocket, /@ServerEndpoint\("\/tutoring\/ws\/messages\/\{matchId\}\/\{token\}"\)/)
assert.match(webSocket, /broadcastMatch/)
assert.match(configSql, /\/system\/tutoring\/ws\/messages\/\*\*/)
